import { FieldRegistry } from "./fieldRegistry";

export interface GeneratedFormFieldOption {
	label?: string
	value?: string
}

export interface GeneratedFormField {
	type: string
	name?: string
	label?: string
	placeholder?: string
	required?: boolean
	options?: GeneratedFormFieldOption[]
}

export interface GeneratedFormJson {
	id?: string
	title?: string
	description?: string
	submitLabel?: string
	fields?: GeneratedFormField[]
}

export interface GeneratedForm {
	id: string
	title: string
	html: string
	css: string
	json: GeneratedFormJson
}

export interface TransmuteResult {
	filename: string
	code: string
	componentName: string
}

function toPascalCase(input: string): string {
	return (input || "GeneratedForm")
		.replace(/[^a-z0-9]+/gi, " ")
		.split(" ")
		.filter(Boolean)
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join("");
}

function escapeJsx(text: string | undefined): string {
	if (!text) return "";
	return String(text)
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;");
}

function renderFieldToJsx(field: GeneratedFormField): string {
	const name = escapeJsx(field.name || field.label || "field");
	const label = escapeJsx(field.label || name);
	const placeholder = escapeJsx(field.placeholder || "");
	const required = field.required ? " required" : "";

	switch ((field.type || "text").toLowerCase()) {
		case "textarea":
			return [`<label>`, `  <span>${label}</span>`, `  <textarea name="${name}" placeholder="${placeholder}"${required}></textarea>`, `</label>`].join("\n");

		case "select": {
			const options = (field.options || [])
				.map((o) => `    <option value="${escapeJsx(o.value || "")}">${escapeJsx(o.label || o.value || "")}</option>`)
				.join("\n");
			return [`<label>`, `  <span>${label}</span>`, `  <select name="${name}"${required}>`, options, `  </select>`, `</label>`].join("\n");
		}

		case "checkbox":
			return `<label><input type="checkbox" name="${name}" aria-label="${label}"${required}/> ${label}</label>`;

		case "radio": {
			const options = (field.options || [])
				.map((o, i) => `  <label><input type="radio" name="${name}" value="${escapeJsx(o.value || String(i))}" aria-label="${escapeJsx(o.label || o.value || String(i))}"${required}/> ${escapeJsx(o.label || o.value || String(i))}</label>`)
				.join("\n");
			return [`<fieldset>`, `  <legend>${label}</legend>`, options, `</fieldset>`].join("\n");
		}

		case "email":
		case "number":
		case "password":
		case "date":
		case "text":
		default: {
			const type = ["email", "number", "password", "date", "text"].includes((field.type || "").toLowerCase())
				? (field.type as string).toLowerCase()
				: "text";
			return [`<label>`, `  <span>${label}</span>`, `  <input type="${type}" name="${name}" placeholder="${placeholder}"${required}/>`, `</label>`].join("\n");
		}
	}
}

export function convertFormToTSX(form: GeneratedForm): TransmuteResult {
	const json = form.json || {};
	const gens = (json.fields || []).map((f) => FieldRegistry[(f.type || "text").toLowerCase()]?.(f as any, "tsx"));
	const fields = gens.map((g, i) => g?.ui.tsx || renderFieldToJsx((json.fields || [])[i] as any)).join("\n  ");
	const stateLines = gens.map((g) => g?.state?.tsx).filter(Boolean) as string[];
	const collectLines = gens.map((g) => g?.collect?.tsx).filter(Boolean) as string[];
	const validateLines = gens.map((g) => g?.validate?.tsx).filter(Boolean) as string[];
	const componentName = toPascalCase(json.title || form.title || "GeneratedForm");
	const submitLabel = escapeJsx(json.submitLabel || "Submit");
	const description = escapeJsx(json.description || "");

	const code = `/*\n  Auto-generated by Buildit codeTransmute\n  Source Form: ${escapeJsx(json.title || form.title)} (${form.id})\n  Original CSS included below as a convenience.\n*/\nimport React from 'react'\n\nexport interface ${componentName}Props {\n  onSubmit?: (event: React.FormEvent<HTMLFormElement>) => void\n}\n\nexport const ${componentName}: React.FC<${componentName}Props> = ({ onSubmit }) => {\n  // Field state\n${stateLines.map((l) => `\t${l}`).join("\n")}\n  const [errorsMap, setErrorsMap] = React.useState<Record<string, string>>({})\n\n  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {\n    e.preventDefault()\n    const formData: Record<string, any> = {}\n    const errors: Record<string, string> = {}\n${collectLines.map((l) => `\t${l}`).join("\n")}\n${validateLines.map((l) => `\t${l}`).join("\n")}\n    if (Object.keys(errors).length > 0) {\n      setErrorsMap(errors)\n      return\n    }\n    setErrorsMap({})\n    onSubmit?.(e)\n  }\n\n  return (\n    <form className=\"buildit-form\" onSubmit={handleSubmit}>\n      <h2>${escapeJsx(json.title || form.title || "Generated Form")}</h2>\n      {${JSON.stringify(description)} && <p className=\"desc\">${description}</p>}\n      {Object.keys(errorsMap).length > 0 && (\n        <div className=\"errors\" style={{color:'#fca5a5'}}>\n          <ul>\n            {Object.entries(errorsMap).map(([k,v]) => (<li key={k}>{v}</li>))}\n          </ul>\n        </div>\n      )}\n      {/* Fields */}\n      <div className=\"fields\">\n        {/* Generated fields start */}\n        {/* eslint-disable jsx-a11y/label-has-associated-control */}\n        {/* The following markup is intentionally simple and uncontrolled */}\n        {/* prettier-ignore */}\n        <>\n  ${fields.split("\n").map((l) => (l ? `        ${l}` : l)).join("\n")}\n        </>\n      </div>\n      <button type=\"submit\" className=\"btn\">${submitLabel}</button>\n    </form>\n  )\n}\n\nexport default ${componentName}\n\n/* Optional CSS (copy into your stylesheet)\n${form.css || ""}\n*/\n`;

	return {
		filename: `${componentName}.tsx`,
		code,
		componentName
	};
}

export function convertFormToJSX(form: GeneratedForm): TransmuteResult {
	const json = form.json || {};
	const gens = (json.fields || []).map((f) => FieldRegistry[(f.type || "text").toLowerCase()]?.(f as any, "jsx"));
	const fields = gens.map((g, i) => g?.ui.jsx || renderFieldToJsx((json.fields || [])[i] as any)).join("\n  ");
	const stateLines = gens.map((g) => g?.state?.jsx).filter(Boolean) as string[];
	const collectLines = gens.map((g) => g?.collect?.jsx).filter(Boolean) as string[];
	const validateLines = gens.map((g) => g?.validate?.jsx).filter(Boolean) as string[];
	const componentName = toPascalCase(json.title || form.title || "GeneratedForm");
	const submitLabel = escapeJsx(json.submitLabel || "Submit");
	const description = escapeJsx(json.description || "");

	const code = `/*\n  Auto-generated by Buildit codeTransmute (JSX)\n  Source Form: ${escapeJsx(json.title || form.title)} (${form.id})\n*/\nimport React from 'react'\n\nexport default function ${componentName}({ onSubmit }) {\n${stateLines.map((l) => `  ${l}`).join("\n")}\n  const [errorsMap, setErrorsMap] = React.useState({})\n  const handleSubmit = (e) => {\n    e.preventDefault()\n    const formData = {}\n    const errors = {}\n${collectLines.map((l) => `    ${l}`).join("\n")}\n${validateLines.map((l) => `    ${l}`).join("\n")}\n    if (Object.keys(errors).length > 0) {\n      setErrorsMap(errors)\n      return\n    }\n    setErrorsMap({})\n    if (typeof onSubmit === 'function') onSubmit(e)\n  }\n  return (\n    <form className=\"buildit-form\" onSubmit={handleSubmit}>\n      <h2>${escapeJsx(json.title || form.title || "Generated Form")}</h2>\n      {${JSON.stringify(description)} && <p className=\"desc\">${description}</p>}\n      {Object.keys(errorsMap).length > 0 && (\n        <div className=\"errors\" style={{color:'#fca5a5'}}>\n          <ul>\n            {Object.entries(errorsMap).map(([k,v]) => (<li key={k}>{v}</li>))}\n          </ul>\n        </div>\n      )}\n      {/* prettier-ignore */}\n      <>\n  ${fields.split("\n").map((l) => (l ? `        ${l}` : l)).join("\n")}\n      </>\n      <button type=\"submit\" className=\"btn\">${submitLabel}</button>\n    </form>\n  )\n}\n\n/* Optional CSS\n${form.css || ""}\n*/\n`;

	return { filename: `${componentName}.jsx`, code, componentName };
}

export function convertFormToTS(form: GeneratedForm): TransmuteResult {
	const componentName = toPascalCase(form.json?.title || form.title || "GeneratedForm");
	const fields = (form.json?.fields || []).map((f) => renderFieldToJsx(f as any)).join("\n  ");
	const html = `\n<form class=\"buildit-form\">\n  <h2>${escapeJsx(form.json?.title || form.title || "Generated Form")}</h2>\n  ${form.json?.description ? `<p class=\\\"desc\\\">${escapeJsx(form.json?.description)}</p>` : ""}\n  ${fields}\n  <button type=\"submit\" class=\"btn\">${escapeJsx(form.json?.submitLabel || "Submit")}</button>\n</form>\n`;

	const code = `/*\n  Auto-generated by Buildit codeTransmute (TypeScript module)\n  Source Form: ${escapeJsx(form.json?.title || form.title)} (${form.id})\n*/\nexport const ${componentName}Html: string = ${JSON.stringify(html)};\nexport const ${componentName}Css: string = ${JSON.stringify(form.css || "")};\nexport const ${componentName}Json = ${JSON.stringify(form.json || {}, null, 2)} as const;\n\nexport function render${componentName}(container: HTMLElement, onSubmit?: (event: SubmitEvent) => void): void {\n  container.innerHTML = ${componentName}Html;\n  const form = container.querySelector('form');\n  if (form) {\n    form.addEventListener('submit', (e) => {\n      e.preventDefault();\n      onSubmit?.(e as SubmitEvent);\n    });\n  }\n}\n`;
	return { filename: `${componentName}.ts`, code, componentName };
}

export function convertFormToJS(form: GeneratedForm): TransmuteResult {
	const componentName = toPascalCase(form.json?.title || form.title || "GeneratedForm");
	const htmlFields = (form.json?.fields || []).map((f) => renderFieldToJsx(f as any)).join(" ");
	const html = `\n<form class=\"buildit-form\">\n  <h2>${escapeJsx(form.json?.title || form.title || "Generated Form")}</h2>\n  ${form.json?.description ? `<p class=\\\"desc\\\">${escapeJsx(form.json?.description)}</p>` : ""}\n  ${htmlFields}\n  <button type=\"submit\" class=\"btn\">${escapeJsx(form.json?.submitLabel || "Submit")}</button>\n</form>\n`;

	const code = `/*\n  Auto-generated by Buildit codeTransmute (JavaScript module)\n  Source Form: ${escapeJsx(form.json?.title || form.title)} (${form.id})\n*/\nexport const html = ${JSON.stringify(html)};\nexport const css = ${JSON.stringify(form.css || "")};\nexport const json = ${JSON.stringify(form.json || {}, null, 2)};\n\nexport function render(container, onSubmit) {\n  container.innerHTML = html;\n  const form = container.querySelector('form');\n  if (form) {\n    form.addEventListener('submit', (e) => {\n      e.preventDefault();\n      if (typeof onSubmit === 'function') onSubmit(e);\n    });\n  }\n}\n`;
	return { filename: `${componentName}.js`, code, componentName };
}

export function convertFormToVue(form: GeneratedForm): TransmuteResult {
	const json = form.json || {};
	const componentName = toPascalCase(json.title || form.title || "GeneratedForm");
	const gens = (json.fields || []).map((f) => FieldRegistry[(f.type || "text").toLowerCase()]?.(f as any, "vue"));
	const fields = gens.map((g, i) => g?.ui.vue || renderFieldToJsx((json.fields || [])[i] as any)).join("\n    ");
	const stateLines = gens.map((g) => g?.state?.vue).filter(Boolean) as string[];
	const collectLines = gens.map((g) => g?.collect?.vue).filter(Boolean) as string[];
	const validateLines = gens.map((g) => g?.validate?.vue).filter(Boolean) as string[];

	const code = `<!--\n  Auto-generated by Buildit codeTransmute (Vue SFC)\n  Source Form: ${escapeJsx(json.title || form.title)} (${form.id})\n-->\n<template>\n  <form class=\"buildit-form\" @submit.prevent=\"onSubmit\">\n    <h2>${escapeJsx(json.title || form.title || "Generated Form")}</h2>\n    ${json.description ? `<p class=\"desc\">${escapeJsx(json.description)}</p>` : ""}\n    <div v-if=\"Object.keys(errorsMap).length\" class=\"errors\" style=\"color:#fca5a5\">\n      <ul>\n        <li v-for=\"(msg, key) in errorsMap\" :key=\"key\">{{ msg }}</li>\n      </ul>\n    </div>\n    <!-- Generated fields start -->\n    ${fields}\n    <button type=\"submit\" class=\"btn\">${escapeJsx(json.submitLabel || "Submit")}</button>\n  </form>\n</template>\n\n<script setup lang=\"ts\">\nimport { ref, reactive } from 'vue'\nconst emit = defineEmits<{ (e: 'submit', event: SubmitEvent): void }>()\n${stateLines.join("\n")}\nconst errorsMap = reactive<Record<string, string>>({})\nfunction onSubmit(event: SubmitEvent) {\n  const formData: Record<string, any> = {}\n  const errors: Record<string, string> = {}\n${collectLines.map((l) => `  ${l}`).join("\n")}\n${validateLines.map((l) => `  ${l}`).join("\n")}\n  // sync errors into reactive map\n  Object.keys(errorsMap).forEach(k => delete (errorsMap as any)[k])\n  for (const [k,v] of Object.entries(errors)) (errorsMap as any)[k] = v\n  if (Object.keys(errors).length === 0) emit('submit', event)\n}\n</script>\n\n<style scoped>\n${form.css || ""}\n</style>\n`;
	return { filename: `${componentName}.vue`, code, componentName };
}

